language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - true

script:
  - export INTERPRETER=python
  - sbin/exabgp --version
  - set pipefail
  - ./qa/bin/parsing | perl -pe 's/^ +//; s/\r/\t\t/g;'
  - ./qa/bin/conversation
