language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - true

script:
  - export INTERPRETER=python
  - sbin/exabgp --version
  - sbin/exabgp --fi > etc/exabgp/exabgp.env
  - set pipefail
  - ./qa/bin/parsing
  - ./qa/bin/conversation
