language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install coveralls

script:
  - export INTERPRETER=python
  - sbin/exabgp --version
  - sbin/exabgp --fi > etc/exabgp/exabgp.env
  - set pipefail
  - ./qa/bin/parsing
  - ./qa/bin/conversation
  - env ETC=`pwd`/etc/exabgp exabgp_log_enable=false nosetests --with-coverage ./qa/tests/
#  - coverage run -m unittest discover -s qa/tests -p *_test.py

after_success:
  - coveralls

sudo: false
